version: '2'
services:
  client:
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - '27017:27017'      
  api:
    build: ./api
    command: [ "npm", "start" ]
    environment: 
      MONGODB_URI: mongodb://mongo:27017/contact_db
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    volumes:
     - ./api:/usr/src/app
     - /usr/src/app/node_modules
